version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped