apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-cheeserun-ingress
  namespace: frontrun
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: localhost  # Puedes cambiar esto por tu dominio
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-app-service
                port:
                  number: 4000  # Cambiado a 4000 ya que es el puerto de la aplicación